import { PRESERVED_LOCAL_STORAGE_PREFIXES } from "@/utils/browserLocalStorageUi";

export const STORE_CONFIG = {
  clearMutationsMapping: {
    currencies: "SET_CURRENCIES",
    units: "SET_UNITS",
    users: "SET_USERS",
    orderStatuses: "SET_ORDER_STATUSES",
    projectStatuses: "SET_PROJECT_STATUSES",
    taskStatuses: "SET_TASK_STATUSES",
    transactionCategories: "SET_TRANSACTION_CATEGORIES",
    roles: "SET_ROLES",
    leaveTypes: "SET_LEAVE_TYPES",
    orderStatusCategories: "SET_ORDER_STATUS_CATEGORIES",
    warehouses: "SET_WAREHOUSES",
    cashRegisters: "SET_CASH_REGISTERS",
    clients: "SET_CLIENTS",
    categories: "SET_CATEGORIES",
    projects: "SET_PROJECTS",
    orders: "SET_ORDERS",
    holidays: "CLEAR_HOLIDAYS",
  },

  globalReferenceFields: [
    "units",
    "currencies",
    "users",
    "orderStatuses",
    "projectStatuses",
    "taskStatuses",
    "transactionCategories",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
  ],

  companyDataFields: [
    "warehouses",
    "cashRegisters",
    "clients",
    "clientsData",
    "lastProducts",
    "allProducts",
    "lastProductsData",
    "allProductsData",
    "categories",
    "projects",
    "projectsData",
    "orders",
    "ordersData",
  ],

  fieldsWithTimestamp: [
    "units",
    "currencies",
    "users",
    "orderStatuses",
    "projectStatuses",
    "taskStatuses",
    "transactionCategories",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
    "warehouses",
    "cashRegisters",
    "clientsData",
    "categories",
    "projectsData",
    "ordersData",
    "lastProductsData",
    "allProductsData",
  ],

  clientTypeFilterValues: [
    "individual",
    "company",
    "employee",
    "investor",
  ],

  localStorageKeys: {
    persistKey: "hasap_vuex_cache",
    referencesCache: "hasap_references_cache",
    userSettings: "hasap_user_settings",
    companyContextSync: "hasap_company_context_sync",
    authUser: "hasap_auth_user",
    preservePrefixes: [...PRESERVED_LOCAL_STORAGE_PREFIXES],
    removePatterns: ["transaction", "balance"],
  },

  cacheVersion: "1.9",

  storageTestKey: "__vuex_test__",

  referencesCacheFields: [
    "warehouses",
    "cashRegisters",
    "clientsData",
    "categories",
    "projectsData",
    "projectsDataCompanyId",
    "ordersData",
    "ordersDataCompanyId",
    "lastProductsData",
    "allProductsData",
  ],

  userSettingsFields: [
    "currentCompany",
    "lastCompanyId",
    "userCompanies",
    "uiTheme",
    "soundEnabled",
    "clientTypeFilter",
    "cashRegisterFilter",
    "clientBalancesCurrencyId",
    "menuItems",
    "kanbanCardFields",
    "kanbanCardFieldDateModes",
    "viewModes",
    "cardFields",
    "cardGridColumns",
    "newsFilters",
  ],

  loadingFlagsToReset: [
    "warehouses",
    "cashRegisters",
    "clients",
    "categories",
    "projects",
    "orders",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
    "projectContracts",
    "holidays",
    "leaves",
  ],

  cacheTTL: {
    lastProductsData: 5 * 60 * 1000,
  },

  fieldTTLMapping: {
    warehouses: "warehouses",
    cashRegisters: "cashRegisters",
    clientsData: "clients",
    categories: "categories",
    projectsData: "projects",
    ordersData: "orders",
    allProductsData: "products",
  },

  uiPreferencesMetaKey: "hasap_ui_prefs_meta",
  uiPreferencesFlushDebounceMs: 2000,
  uiPreferencesLsBatchSize: 30,
  uiPreferencesHydrateChunkSize: 15,

  uiPreferencesVuexFields: [
    "uiTheme",
    "soundEnabled",
    "menuItems",
    "kanbanCardFields",
    "kanbanCardFieldDateModes",
    "viewModes",
    "cardGridColumns",
    "newsFilters",
  ],

  uiPreferencesLsPrefixes: [
    "tableColumns_",
    "tableSort_",
    "cardFields_",
    "ui_cash_register_user_colors_",
    "ui_transactions_balance_cards_layout_",
    "cardGridColumns_",
  ],

  uiPreferencesLsExactKeys: [
    "kanban_column_order_orders",
    "kanban_column_order_projects",
    "kanban_column_order_tasks",
    "kanban_column_order_leads",
    "perPage",
    "reportByCategoriesFilters",
  ],

  uiPreferencesLsUserPrefixes: ["simple_services_order_"],

  uiPreferencesVuexMutations: [
    "SET_UI_THEME",
    "SET_SOUND_ENABLED",
    "SET_MENU_ITEMS",
    "UPDATE_KANBAN_CARD_FIELDS",
    "UPDATE_KANBAN_CARD_FIELD_DATE_MODES",
    "SET_NEWS_FILTERS",
    "SET_LEAVES_VIEW_MODE",
    "SET_PROJECTS_VIEW_MODE",
    "SET_ORDERS_VIEW_MODE",
    "SET_LEADS_VIEW_MODE",
    "SET_TASKS_VIEW_MODE",
    "SET_CLIENTS_VIEW_MODE",
    "SET_USERS_VIEW_MODE",
    "SET_TRANSACTIONS_VIEW_MODE",
    "SET_SALES_VIEW_MODE",
    "SET_INVOICES_VIEW_MODE",
    "SET_TRANSFERS_VIEW_MODE",
    "SET_TRANSACTION_CATEGORIES_VIEW_MODE",
    "SET_LIST_PAGE_VIEW_MODE",
    "SET_CARD_GRID_COLUMNS",
    "RESET_CARD_GRID_COLUMNS",
    "HYDRATE_UI_PREFERENCES_VUEX",
  ],
};

