import { PRESERVED_LOCAL_STORAGE_PREFIXES } from "@/utils/browserLocalStorageUi";

export const STORE_CONFIG = {
  clearMutationsMapping: {
    currencies: "SET_CURRENCIES",
    units: "SET_UNITS",
    users: "SET_USERS",
    orderStatuses: "SET_ORDER_STATUSES",
    projectStatuses: "SET_PROJECT_STATUSES",
    taskStatuses: "SET_TASK_STATUSES",
    transactionCategories: "SET_TRANSACTION_CATEGORIES",
    roles: "SET_ROLES",
    leaveTypes: "SET_LEAVE_TYPES",
    orderStatusCategories: "SET_ORDER_STATUS_CATEGORIES",
    warehouses: "SET_WAREHOUSES",
    cashRegisters: "SET_CASH_REGISTERS",
    clients: "SET_CLIENTS",
    categories: "SET_CATEGORIES",
    projects: "SET_PROJECTS",
  },

  globalReferenceFields: [
    "units",
    "currencies",
    "users",
    "orderStatuses",
    "projectStatuses",
    "taskStatuses",
    "transactionCategories",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
  ],

  companyDataFields: [
    "warehouses",
    "cashRegisters",
    "clients",
    "clientsData",
    "lastProducts",
    "allProducts",
    "lastProductsData",
    "allProductsData",
    "categories",
    "projects",
    "projectsData",
  ],

  fieldsWithTimestamp: [
    "units",
    "currencies",
    "users",
    "orderStatuses",
    "projectStatuses",
    "taskStatuses",
    "transactionCategories",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
    "warehouses",
    "cashRegisters",
    "clientsData",
    "categories",
    "projectsData",
    "lastProductsData",
    "allProductsData",
  ],

  clientTypeFilterValues: [
    "individual",
    "company",
    "employee",
    "investor",
  ],

  localStorageKeys: {
    persistKey: "hasap_vuex_cache",
    referencesCache: "hasap_references_cache",
    userSettings: "hasap_user_settings",
    companyContextSync: "hasap_company_context_sync",
    authUser: "hasap_auth_user",
    preservePrefixes: [...PRESERVED_LOCAL_STORAGE_PREFIXES],
    removePatterns: ["transaction", "balance"],
  },

  cacheVersion: "1.0",

  storageTestKey: "__vuex_test__",

  referencesCacheFields: [
    "warehouses",
    "cashRegisters",
    "clientsData",
    "categories",
    "projectsData",
    "projectsDataCompanyId",
    "lastProductsData",
    "allProductsData",
  ],

  userSettingsFields: [
    "currentCompany",
    "lastCompanyId",
    "userCompanies",
    "uiTheme",
    "soundEnabled",
    "orderStatusesCustomOrder",
    "clientTypeFilter",
    "cashRegisterFilter",
    "clientBalancesCurrencyId",
    "menuItems",
    "kanbanCardFields",
    "viewModes",
    "cardFields",
    "newsFilters",
  ],

  loadingFlagsToReset: [
    "warehouses",
    "cashRegisters",
    "clients",
    "categories",
    "projects",
    "roles",
    "leaveTypes",
    "orderStatusCategories",
    "projectContracts",
    "companyHolidays",
    "leaves",
  ],

  cacheTTL: {
    lastProductsData: 5 * 60 * 1000,
  },

  fieldTTLMapping: {
    warehouses: "warehouses",
    cashRegisters: "cashRegisters",
    clientsData: "clients",
    categories: "categories",
    projectsData: "projects",
    allProductsData: "products",
  },
};

