export const FILTER_FIELD_ICONS = {
  cashRegister: 'fas fa-cash-register',
  transactionType: 'fas fa-right-left',
  source: 'fas fa-link',
  project: 'fas fa-diagram-project',
  debt: 'fas fa-hand-holding-dollar',
  date: 'fas fa-calendar-day',
  startDate: 'fas fa-calendar-day',
  endDate: 'fas fa-calendar-check',
  status: 'fas fa-list-check',
  client: 'fas fa-user-group',
  category: 'fas fa-tags',
  type: 'fas fa-shapes',
  warehouse: 'fas fa-warehouse',
  user: 'fas fa-user-tie',
  paid: 'fas fa-check-double',
  product: 'fas fa-box',
  availability: 'fas fa-boxes-stacked',
  reason: 'fas fa-comment-dots',
};
